export const PROJECTS = [
  {
    image: "/projects/lbg-website.png",
    title: "LaunchBox Global",
    description:
      "A modern tech company website built from scratch using Figma, Next.js, Tailwind CSS, and Framer Motion. Designed and developed a fully responsive, cross-browser compatible platform with optimized performance, effectively showcasing the company’s identity, services, and development expertise.",
    url: "https://launchboxglobal.com/",
    code_url: null,
    type: "Website",
    tech_stack: [
      "Nextjs",
      "Tailwind CSS",
      "Framer Motion",
      "Responsive",
      "Cross-Browser Compatibility",
      "Performance Optimization",
    ],
  },
  {
    image: "/projects/carveeps-mockup.png",
    title: "Carveeps",
    description:
      "Developed the Manager Panel for a multi-role car service platform (Users, Managers, Admin) that enables businesses to manage services such as car washes, oil changes, and maintenance operations. Focused on clean UI/UX, efficient data flow, and maintainable component architecture to ensure a smooth operational experience for users.",
    url: "https://app.carveeps.com/",
    type: "Web App",
    tech_stack: [
      "Reactjs",
      "Tailwind CSS",
      "Stripe",
      "Context API",
      "Axios",
      "API Integration",
    ],
  },
  {
    image: "/projects/giveXchange.png",
    title: "giveXchange",
    description:
      "Developed the complete frontend of a multi-interface community-driven e-commerce platform, enabling users to buy and sell products within localized community networks. Translated Figma designs into three fully functional interfaces: Admin Dashboard, Community Owner Portal, and Buyer/Seller UI. Focused on modular architecture, reusable components, and responsive design to ensure maintainability and scalability across complex multi-role workflows.",
    url: "https://user.thegivexchange.com/",
    type: "Web App",
    tech_stack: [
      "Reactjs",
      "Tailwind CSS",
      "Stripe",
      "Redux Toolkit",
      "Redux Toolkit Query",
      "API Integration",
      "Product Catalog",
      "Order Management",
      "e-Commerce",
    ],
  },
  {
    image: "/projects/markettoll.png",
    title: "Markettoll",
    description:
      "Built the complete frontend of a full-stack e-commerce platform from scratch using React (Vite), translating Figma designs into a responsive and production-ready user interface. Integrated RESTful APIs to support core e-commerce workflows including product management, order processing, and order history. Focused on clean architecture, reusable components, and seamless user experience across the entire purchase journey.",
    url: "https://markettoll.com/",
    type: "Web App",
    tech_stack: [
      "Reactjs",
      "Tailwind CSS",
      "Stripe",
      "Context API",
      "REST API Integration",
      "Axios",
      "Firebase",
      "Product Catalog",
    ],
  },
  {
    image: "/projects/library-management-system-mockup.png",
    title: "Library Management System",
    description:
      "A full-stack Library Management System built using the MERN Stack. The system provides role-based access for Admins and Students, allowing efficient management of books, student accounts, and borrowing requests.",
    url: "https://library-management-system-student-portal.vercel.app/login",
    code_url: "https://github.com/shoaibmuhammad-dev/Library-Management-System",
    type: "Website App",
    tech_stack: [
      "Reactjs",
      "Nodejs",
      "Expressjs",
      "MongoDB",
      "Redux Toolkit",
      "RTK Query",
      "Tailwind CSS",
      "JWT",
    ],
  },
  {
    image: "/projects/spartax-mockup.png",
    title: "Spartax",
    description:
      "A full-stack eCommerce platform built using the MERN Stack with role-based access for Admin and Buyers. Implemented product management, order tracking, analytics dashboard, and a seamless shopping experience with filtering, cart functionality, and secure Stripe checkout integration.",
    // url: "https://spartax.vercel.app/",
    url: null,
    code_url: "https://github.com/shoaibmuhammad-dev/E-commerce-Store.git",
    type: "Ecommerce Website",
    tech_stack: [
      "Reactjs",
      "Nodejs",
      "Expressjs",
      "MongoDB",
      "Redux Toolkit",
      "RTK Query",
      "Stripe",
      "Tailwind CSS",
    ],
  },
  {
    image: "/projects/nobroker.png",
    title: "NoBroker",
    description:
      "A static real estate website developed for a client using HTML, Tailwind CSS, and JavaScript. Accurately replicated an existing design with a fully responsive, cross-browser compatible layout, delivering a pixel-perfect clone aligned with client requirements.",
    url: "https://no-broker-website.vercel.app/",
    code_url:
      "https://github.com/shoaibmuhammad-dev/nobroker-real-estate-wesbite.git",
    type: "Website",
    tech_stack: ["HTML", "CSS", "Tailwind CSS", "JavaScript"],
  },
  // {
  //   image: "/projects/dignite-studios-website.png",
  //   title: "Dignite Studios",
  //   description: "",
  //   url: "https://www.dignitestudios.com/",
  //   type: "Website",
  //   tech_stack: ["Nextjs", "Tailwind CSS", "Framer Motion"],
  // },
  {
    image: "/projects/8.png",
    title: "NYKN",
    description:
      "Created an engaging landing page for a mobile travel app that uncovers Nashville’s hidden history and local secrets. Structured content to effectively communicate unique value propositions, including curated recommendations across multiple categories and a guided 3-hour tour. Focused on storytelling-driven design and intuitive layout to appeal to both tourists and locals.",
    url: "https://www.nowyouknownashville.com/",
    type: "Landing Page",
    tech_stack: ["Reactjs", "Tailwind CSS"],
  },
  {
    image: "/projects/my-garage-outlet-landing-page.png",
    title: "My Garage Outlet",
    description:
      "Designed and developed a high-conversion landing page for a mobile app focused on discovering, hosting, and connecting through local garage sales. Built a clean, user-friendly interface that highlights core features such as event discovery, hosting tools, and community engagement. Emphasized responsive design and smooth UI interactions to enhance user acquisition.",
    url: "https://www.mygarageoutlet.com/",
    type: "Landing Page",
    tech_stack: ["Reactjs", "Tailwind CSS"],
  },
  {
    image: "/projects/6.png",
    title: "Bioyap",
    description:
      "Developed a modern landing page for a professional networking app tailored to pharma industry professionals. Designed to clearly present the platform’s value in fostering connections, collaboration, and career growth. Prioritized clarity, accessibility, and a polished visual hierarchy to target a professional audience.",
    url: "https://www.bioyap.com/",
    type: "Landing Page",
    tech_stack: ["Reactjs", "Tailwind CSS"],
  },
];
