export const PROJECTS = [
  {
    image: "/projects/lbg-website.png",
    title: "LaunchBox Global",
    description: "",
    url: "https://launchboxglobal.com/",
    type: "Website",
    tech_stack: [
      "Nextjs",
      "Tailwind CSS",
      "Framer Motion",
    ],
  },
  {
    image: "/projects/carveeps-mockup.png",
    title: "Carveeps",
    description: "",
    url: "https://app.carveeps.com/",
    type: "Web App",
    tech_stack: [
      "Reactjs",
      "Nodejs",
      "Expressjs",
      "MongoDB",
      "Tailwind CSS",
      "Stripe",
    ],
  },
  {
    image: "/projects/personal-portfolio-project-mockup.png",
    title: "Personal Portfolio",
    description: "",
    url: "https://shoaib-muhammad.vercel.app/",
    type: "Website",
    tech_stack: ["Reactjs", "Tailwind CSS", "Framer Motion"],
  },
  // {
  //   image: "/projects/dignite-studios-website.png",
  //   title: "Dignite Studios",
  //   description: "",
  //   url: "https://www.dignitestudios.com/",
  //   type: "Website",
  //   tech_stack: ["Nextjs", "Tailwind CSS", "Framer Motion"],
  // },
  {
    image: "/projects/spartax-mockup.png",
    title: "Spartax",
    description: "",
    url: "https://spartax.vercel.app/",
    type: "Ecommerce Website",
    tech_stack: ["Reactjs", "Tailwind CSS"],
  },
  {
    image: "/projects/8.png",
    title: "NYKN",
    description: "",
    url: "https://www.nowyouknownashville.com/",
    type: "Landing Page",
    tech_stack: ["Reactjs", "Tailwind CSS"],
  },
  {
    image: "/projects/my-garage-outlet-landing-page.png",
    title: "My Garage Outlet",
    description: "",
    url: "https://www.mygarageoutlet.com/",
    type: "Landing Page",
    tech_stack: ["Reactjs", "Tailwind CSS"],
  },
  {
    image: "/projects/6.png",
    title: "Bioyap",
    description: "",
    url: "https://www.bioyap.com/",
    type: "Landing Page",
    tech_stack: ["Reactjs", "Tailwind CSS"],
  },
   {
    image: "/projects/nobroker.png",
    title: "NoBroker",
    description: "",
    url: "https://no-broker-website.vercel.app/",
    type: "Website",
    tech_stack: ["HTML", "Tailwind CSS", "JavaScript"],
  },
];

//personal-portfolio-project-mockup
