export const PROJECTS = [
  {
    image: "/projects/lbg-website.png",
    title: "LaunchBox Global",
    description:
      "A modern tech company website built from scratch using Figma, Next.js, Tailwind CSS, and Framer Motion. Designed and developed a fully responsive, cross-browser compatible platform with optimized performance, effectively showcasing the company’s identity, services, and development expertise.",
    url: "https://launchboxglobal.com/",
    code_url: null,
    type: "Website",
    tech_stack: [
      "Nextjs",
      "Tailwind CSS",
      "Framer Motion",
      "Responsive",
      "Cross-Browser Compatibility",
      "Performance Optimization",
    ],
  },
  {
    image: "/projects/library-management-system-mockup.png",
    title: "Library Management System",
    description:
      "A full-stack Library Management System built using the MERN Stack. The system provides role-based access for Admins and Students, allowing efficient management of books, student accounts, and borrowing requests.",
    url: null,
    code_url: "https://github.com/shoaibmuhammad-dev/Library-Management-System",
    type: "Website App",
    tech_stack: [
      "Reactjs",
      "Nodejs",
      "Expressjs",
      "MongoDB",
      "Redux Toolkit",
      "RTK Query",
      "Tailwind CSS",
      "JWT",
    ],
  },
  {
    image: "/projects/spartax-mockup.png",
    title: "Spartax",
    description:
      "A full-stack eCommerce platform built using the MERN Stack with role-based access for Admin and Buyers. Implemented product management, order tracking, analytics dashboard, and a seamless shopping experience with filtering, cart functionality, and secure Stripe checkout integration.",
    url: "https://spartax.vercel.app/",
    code_url: "https://github.com/shoaibmuhammad-dev/E-commerce-Store.git",
    type: "Ecommerce Website",
    tech_stack: [
      "Reactjs",
      "Nodejs",
      "Expressjs",
      "MongoDB",
      "Redux Toolkit",
      "RTK Query",
      "Stripe",
      "Tailwind CSS",
    ],
  },
  {
    image: "/projects/nobroker.png",
    title: "NoBroker",
    description:
      "A static real estate website developed for a client using HTML, Tailwind CSS, and JavaScript. Accurately replicated an existing design with a fully responsive, cross-browser compatible layout, delivering a pixel-perfect clone aligned with client requirements.",
    url: "https://no-broker-website.vercel.app/",
    code_url:
      "https://github.com/shoaibmuhammad-dev/nobroker-real-estate-wesbite.git",
    type: "Website",
    tech_stack: ["HTML", "CSS", "Tailwind CSS", "JavaScript"],
  },
  // {
  //   image: "/projects/carveeps-mockup.png",
  //   title: "Carveeps",
  //   description: "",
  //   url: "https://app.carveeps.com/",
  //   type: "Web App",
  //   tech_stack: [
  //     "Reactjs",
  //     "Nodejs",
  //     "Expressjs",
  //     "MongoDB",
  //     "Tailwind CSS",
  //     "Stripe",
  //   ],
  // },
  // {
  //   image: "/projects/personal-portfolio-project-mockup.png",
  //   title: "Personal Portfolio",
  //   description: "",
  //   url: "https://shoaib-muhammad.vercel.app/",
  //   type: "Website",
  //   tech_stack: ["Reactjs", "Tailwind CSS", "Framer Motion"],
  // },
  // {
  //   image: "/projects/dignite-studios-website.png",
  //   title: "Dignite Studios",
  //   description: "",
  //   url: "https://www.dignitestudios.com/",
  //   type: "Website",
  //   tech_stack: ["Nextjs", "Tailwind CSS", "Framer Motion"],
  // },
  // {
  //   image: "/projects/8.png",
  //   title: "NYKN",
  //   description: "",
  //   url: "https://www.nowyouknownashville.com/",
  //   type: "Landing Page",
  //   tech_stack: ["Reactjs", "Tailwind CSS"],
  // },
  // {
  //   image: "/projects/my-garage-outlet-landing-page.png",
  //   title: "My Garage Outlet",
  //   description: "",
  //   url: "https://www.mygarageoutlet.com/",
  //   type: "Landing Page",
  //   tech_stack: ["Reactjs", "Tailwind CSS"],
  // },
  // {
  //   image: "/projects/6.png",
  //   title: "Bioyap",
  //   description: "",
  //   url: "https://www.bioyap.com/",
  //   type: "Landing Page",
  //   tech_stack: ["Reactjs", "Tailwind CSS"],
  // },
];
